const Amenities = {
  Pool: 'Pool',
  Gym: 'Gym',
  Lounge: 'Lounge',
  Spa: 'Spa',
  Sauna: 'Sauna',
  HotTub: 'Hot tub',
  ConciergeService: 'Concierge service',
  RooftopDeck: 'Rooftop deck',
  BBQFacilities: 'BBQ facilities',
  TennisCourts: 'Tennis courts',
  MovieTheater: 'Movie theater',
  Playground: 'Playground',
  YogaStudio: 'Yoga studio',
  LaundryFacilities: 'Laundry facilities',
  EVCharging: 'EV charging',
  BikeStorage: 'Bike Storage',
  PackageLockers: 'Package lockers',
  OnsiteSecurity: 'Onsite security',
  FitnessClasses: 'Fitness classes',
  CarWashArea: 'Car wash area',
  CommunityGarden: 'Community garden',
};

export default Amenities;
