export const MultiWordFields = {
  streetAddress: 'Street Address',
  postalCode: 'Postal Code',
  firstName: 'First Name',
  lastName: 'Last Name',
  phoneNumber: 'Phone Number',
  startDate: 'Start Date',
  endDate: 'End Date',
  dueDate: 'Due Date',
  paymentHistory: 'Payment History',
  propertyId: 'Property ID',
  hourlyRate: 'Hourly Rate',
  birthDate: 'Date of Birth',
  leaseFile: 'Lease File',
  leaseType: 'Lease Type',
  feesType: 'Fees Type',
  paymentType: 'Payment Type',
  paidDate: 'Paid Date',
  fullName: 'Full Name',
  profileImageUrl: "Profile Image"
};
