export const MultiWordFields = {
  streetAddress: 'Street address',
  postalCode: 'Postal code',
  firstName: 'First name',
  lastName: 'Last name',
  phoneNumber: 'Phone number',
  startDate: 'Start date',
  endDate: 'End date',
  dueDate: 'Due date',
  paymentHistory: 'Payment history',
  propertyId: 'Property ID',
  hourlyRate: 'Hourly rate',
  birthDate: 'Date of birth',
  leaseFile: 'Lease file',
  leaseType: 'Lease type',
  feesType: 'Fees type',
  paymentType: 'Payment type',
  paidDate: 'Paid date',
};
